language: java
jdk:
- oraclejdk8
services:
  - docker
before_install:
- openssl aes-256-cbc -K $encrypted_7de4f116116e_key -iv $encrypted_7de4f116116e_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
#- scp ./target/springboot-helloworld-1.0-SNAPSHOT.jar root@47.110.46.159:/root/workspace
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t stevencode/springboot-helloworld:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID .
- docker push stevencode/springboot-helloworld:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID;
- ssh root@47.110.46.159 "./root/workspace/deploy.sh $TRAVIS_BRANCH-$TRAVIS_BUILD_ID"
addons:
  ssh_known_hosts: 47.110.46.159
script:
- echo 'hello,world'